This notebook explores and cleans 'final_book_dataset.csv'.
I specifically:
- Removed the column index column
- Turned all entries in title_id into integers
- Turned all author birthyears into integers
- Turned all isbns into strings, so hopefully we get less warnings about this column's dtypes
- I also parsed the raw HTML book_synopsis entries using html2text. Hopefully this results in something better to use

In [2]:
import numpy as np
import pandas as pd

In [3]:
books = pd.read_csv('final_book_dataset.csv', sep='\t')
books = books[['title_id', 'title', 'author', 'release_year',
       'release_date', 'first_publisher', 'author_birthyear',
       'author_birthplace', 'isbn', 'book_synopsis', 'tags', 'hugo', 'locus']]

/tmp/ipykernel_3869/3878242122.py:1: DtypeWarning: Columns (0: isbn) have mixed types. Specify dtype option on import or set low_memory=False.
  books = pd.read_csv('final_book_dataset.csv', sep='\t')

In [4]:
books.title_id = books.title_id.astype('Int64')
books.author_birthyear = books.author_birthyear.astype('Int64')
books.isbn = books.isbn.astype('str')
books.sample(5)

,title_id,title,author,release_year,release_date,first_publisher,author_birthyear,author_birthplace,isbn,book_synopsis,tags,hugo,locus
29604,274081,Last Man Running,Chris Boucher,1999,1999-00-00,BBC Books,1943,"Maldon, Essex, England, UK",0563405945,NaN,[],False,False
7823,3077491,Goldenrod,Mary Towne,1977,1977-09-00,Atheneum,1934,NaN,0689305974,NaN,NaN,False,False
13103,571,Eros Descending,Mike Resnick,1985,1985-12-00,Signet / New American Library,1942,"Chicago, Illinois, USA",0451140176,<b>From the back cover of the Signet first edi...,"['Fiction', 'Science fiction', 'Fantasy']",False,False
92465,2039212,Door Into Faerie,Edward Willett,2016,2016-00-00,Coteau Books,1959,"Silver City, New Mexico, USA",9781550506549.0,In the climactic fifth book of the Shards of E...,NaN,False,False
146504,3337102,Deep Black,Miles Cameron,2024,2024-08-01,Gollancz,1962,"Pittsburgh, Pennsylvania, USA",9781399615037.0,Marca Nbaro had always dreamed of serving aboa...,"['science fiction', 'Fantasy', 'Fiction', 'Sci...",False,False

In [5]:
# Use html2text to parse the descriptions
# Install only once of course
#%pip install -U html2text

In [6]:
import html2text

def exception_handled_htmlparse(x):
    try:
        return html2text.html2text(x)
    except AttributeError:
        if pd.isnull(x):
            return ''
        print(x)
    return x

In [7]:
books.book_synopsis = books.book_synopsis.apply(exception_handled_htmlparse)

In [8]:
books

,title_id,title,author,release_year,release_date,first_publisher,author_birthyear,author_birthplace,isbn,book_synopsis,tags,hugo,locus
0,9372,The Long Loud Silence,Wilson Tucker,1954,1954-00-00,Dell,1914,"Deer Creek, Illinois, USA",0899683754,Publisher's description: Tomorrow's war -- the...,"['Anatomy of Wonder 1 Core Collection', 'biolo...",False,False
1,2215181,Mrs. Candy Strikes It Rich,Robert Tallant,1954,1954-00-00,Doubleday,1909,"New Orleans, Louisiana, USA",NaN,,NaN,False,False
2,1392436,Return to the Lost Planet,Angus MacVicar,1954,1954-00-00,Burke,1908,"Duror, Argyll, Scotland, UK",NaN,,NaN,False,False
3,1112206,Rainbow on the Road,Esther Forbes,1954,1954-00-00,Houghton Mifflin,1891,"Westborough, Massachusetts, USA",NaN,,NaN,False,False
4,1908,The Forgotten Planet,Murray Leinster,1954,1954-00-00,Ace Books,1896,"Norfolk, Virginia, USA",0881846163,"**From the first page of the Ace Double:** ""Na...","['insects', 'Librivox', 'Project Gutenberg', '...",False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
151586,3506914,Daughter of the Underworld,"Katharine Corr, Elizabeth Corr",2025,2025-09-09,Candlewick Press,<NA>,NaN,9781536244533.0,"Join a thrilling journey into the Underworld, ...","['Young Adult Fiction', 'Fantasy', 'Young Adul...",False,False
151587,3506911,We Are Always Tender with Our Dead,Eric LaRocca,2025,2025-09-09,Titan Books,<NA>,"Connecticut, USA",9781803368672.0,A chilling supernatural tale of transgressive ...,"['Fiction', 'LGBTQ', 'Fantasy', 'TBB The Grave...",False,False
151588,3506908,They Fear Not Men in the Woods,Gretchen McNeil,2025,2025-09-09,DAW Books,1983,"San Francisco, California, USA",9780756420086.0,When Jen Monroe hears her father's remains hav...,['Fiction'],False,False
151589,3506905,Press 1 for Invasion,J. A. Dauber,2025,2025-09-09,Aladdin,<NA>,NaN,9781665974776.0,,['juvenile sf'],False,False
151590,<NA>,The Tomb of Dragons,Katherine Addison,2025,NaN,Tor Books,<NA>,NaN,9781250821027.0,Thara Celehar has lost his ability to speak wi...,"['Fantasy', 'Fiction', 'Science Fiction', 'LGB...",False,True

In [ ]:
#books.to_csv('final_book_dataset_cleaned.csv', sep='\t', index=False)

In [10]:
test = pd.read_csv(
    'final_book_dataset_cleaned.csv',
    dtype={
        'isbn' : 'str', # do this explicitly to avoide getting a warning by the interpreter
        'author_birthyear' : 'Int64', # we have to explicitly do this to avoid pandas implicitly casting as float
        'title_id' : 'Int64'
    }, 
    sep='\t'
    )

In [11]:
test

,title_id,title,author,release_year,release_date,first_publisher,author_birthyear,author_birthplace,isbn,book_synopsis,tags,hugo,locus
0,9372,The Long Loud Silence,Wilson Tucker,1954,1954-00-00,Dell,1914,"Deer Creek, Illinois, USA",0899683754,Publisher's description: Tomorrow's war -- the...,"['Anatomy of Wonder 1 Core Collection', 'biolo...",False,False
1,2215181,Mrs. Candy Strikes It Rich,Robert Tallant,1954,1954-00-00,Doubleday,1909,"New Orleans, Louisiana, USA",NaN,NaN,NaN,False,False
2,1392436,Return to the Lost Planet,Angus MacVicar,1954,1954-00-00,Burke,1908,"Duror, Argyll, Scotland, UK",NaN,NaN,NaN,False,False
3,1112206,Rainbow on the Road,Esther Forbes,1954,1954-00-00,Houghton Mifflin,1891,"Westborough, Massachusetts, USA",NaN,NaN,NaN,False,False
4,1908,The Forgotten Planet,Murray Leinster,1954,1954-00-00,Ace Books,1896,"Norfolk, Virginia, USA",0881846163,"**From the first page of the Ace Double:** ""Na...","['insects', 'Librivox', 'Project Gutenberg', '...",False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
151586,3506914,Daughter of the Underworld,"Katharine Corr, Elizabeth Corr",2025,2025-09-09,Candlewick Press,<NA>,NaN,9781536244533.0,"Join a thrilling journey into the Underworld, ...","['Young Adult Fiction', 'Fantasy', 'Young Adul...",False,False
151587,3506911,We Are Always Tender with Our Dead,Eric LaRocca,2025,2025-09-09,Titan Books,<NA>,"Connecticut, USA",9781803368672.0,A chilling supernatural tale of transgressive ...,"['Fiction', 'LGBTQ', 'Fantasy', 'TBB The Grave...",False,False
151588,3506908,They Fear Not Men in the Woods,Gretchen McNeil,2025,2025-09-09,DAW Books,1983,"San Francisco, California, USA",9780756420086.0,When Jen Monroe hears her father's remains hav...,['Fiction'],False,False
151589,3506905,Press 1 for Invasion,J. A. Dauber,2025,2025-09-09,Aladdin,<NA>,NaN,9781665974776.0,NaN,['juvenile sf'],False,False
151590,<NA>,The Tomb of Dragons,Katherine Addison,2025,NaN,Tor Books,<NA>,NaN,9781250821027.0,Thara Celehar has lost his ability to speak wi...,"['Fantasy', 'Fiction', 'Science Fiction', 'LGB...",False,True